[[libidn]]
arch = "aarch64"
git-tree-sha1 = "8e2635c712827914fac5b3c03cf4faf8563e36b4"
os = "macos"

    [[libidn.download]]
    sha256 = "c8a56b2e25827c2ba2cb8fdbb6fa5360edfdeba525fae0e402aa21288c070867"
    url = "https://github.com/JuliaBinaryWrappers/libidn_jll.jl/releases/download/libidn-v1.44.0+0/libidn.v1.44.0.aarch64-apple-darwin.tar.gz"
[[libidn]]
arch = "aarch64"
git-tree-sha1 = "7a929a45c2872c512b740026c864328bcf9dc38a"
libc = "glibc"
os = "linux"

    [[libidn.download]]
    sha256 = "b2e090f2b647a2e0a09d02b9b8984529d42fc137ecd5639a9018d19ab186a75f"
    url = "https://github.com/JuliaBinaryWrappers/libidn_jll.jl/releases/download/libidn-v1.44.0+0/libidn.v1.44.0.aarch64-linux-gnu.tar.gz"
[[libidn]]
arch = "aarch64"
git-tree-sha1 = "01b38909d1e0e9987acead4834002f210c2af575"
libc = "musl"
os = "linux"

    [[libidn.download]]
    sha256 = "73682218501a72070b620723b25025ff0b8f30c601cfe72df069f5bdd37be917"
    url = "https://github.com/JuliaBinaryWrappers/libidn_jll.jl/releases/download/libidn-v1.44.0+0/libidn.v1.44.0.aarch64-linux-musl.tar.gz"
[[libidn]]
arch = "aarch64"
git-tree-sha1 = "44da1a63fe3a8ec72b06737a8a245df6c44b07a6"
os = "freebsd"

    [[libidn.download]]
    sha256 = "59d07aff33e579fb19c5ab073ca78f0c274678948e9d9cae0319b2ee00c9ab2a"
    url = "https://github.com/JuliaBinaryWrappers/libidn_jll.jl/releases/download/libidn-v1.44.0+0/libidn.v1.44.0.aarch64-unknown-freebsd.tar.gz"
[[libidn]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "38dc1efa08c4c3d6930e29a9916bd6cfd9e71d9a"
libc = "glibc"
os = "linux"

    [[libidn.download]]
    sha256 = "9e837a1d963e097726a39d0468278742612a7c6ba480665ba8ad71e42030592e"
    url = "https://github.com/JuliaBinaryWrappers/libidn_jll.jl/releases/download/libidn-v1.44.0+0/libidn.v1.44.0.armv6l-linux-gnueabihf.tar.gz"
[[libidn]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "da30c41ff18f784e0d68eadd5c99bda26471b00a"
libc = "musl"
os = "linux"

    [[libidn.download]]
    sha256 = "8a8a43732ebba2f42e6517dc2f01fab8213e4742a9888148a18c0d2231ba75c3"
    url = "https://github.com/JuliaBinaryWrappers/libidn_jll.jl/releases/download/libidn-v1.44.0+0/libidn.v1.44.0.armv6l-linux-musleabihf.tar.gz"
[[libidn]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ab710157501b2abe8adcc8a5a1682476e86a9505"
libc = "glibc"
os = "linux"

    [[libidn.download]]
    sha256 = "4e3a36092e1a3030d79618ce709b45aef135df91811a4b1b9c0a64e2fb532e3c"
    url = "https://github.com/JuliaBinaryWrappers/libidn_jll.jl/releases/download/libidn-v1.44.0+0/libidn.v1.44.0.armv7l-linux-gnueabihf.tar.gz"
[[libidn]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "54400e788f60203b6696ef4e94f56d2cdebb2787"
libc = "musl"
os = "linux"

    [[libidn.download]]
    sha256 = "8248f01eb1f9d186fa037a2bc773d1ccbafaf799e73d762f5d5615e8b3739422"
    url = "https://github.com/JuliaBinaryWrappers/libidn_jll.jl/releases/download/libidn-v1.44.0+0/libidn.v1.44.0.armv7l-linux-musleabihf.tar.gz"
[[libidn]]
arch = "i686"
git-tree-sha1 = "851f1c09e81e1495e078616981b3db9340a5bc62"
libc = "glibc"
os = "linux"

    [[libidn.download]]
    sha256 = "9ac3db15bac1599ab0826bf2a2ce4aa5d3bbca0767553a6556c1ef6dedaf8577"
    url = "https://github.com/JuliaBinaryWrappers/libidn_jll.jl/releases/download/libidn-v1.44.0+0/libidn.v1.44.0.i686-linux-gnu.tar.gz"
[[libidn]]
arch = "i686"
git-tree-sha1 = "d666feff4c42163e9119d00bc2b71c4cea629303"
libc = "musl"
os = "linux"

    [[libidn.download]]
    sha256 = "285377f06ce80d6318af141586728d2a1a3ace6e587eb2e847d1a0404eb714cf"
    url = "https://github.com/JuliaBinaryWrappers/libidn_jll.jl/releases/download/libidn-v1.44.0+0/libidn.v1.44.0.i686-linux-musl.tar.gz"
[[libidn]]
arch = "i686"
git-tree-sha1 = "3348fefecd6d056f96f814be3f275919410160b1"
os = "windows"

    [[libidn.download]]
    sha256 = "37d7b975bf34107610fa9928917c2e3ce16f4e98b4ddc6f27e1b651626def56e"
    url = "https://github.com/JuliaBinaryWrappers/libidn_jll.jl/releases/download/libidn-v1.44.0+0/libidn.v1.44.0.i686-w64-mingw32.tar.gz"
[[libidn]]
arch = "powerpc64le"
git-tree-sha1 = "1ffddeeb9019bfbf2a97ce5f7c1aca20e0b203f9"
libc = "glibc"
os = "linux"

    [[libidn.download]]
    sha256 = "a5d748128900eb9399de7760fa558f226b3754ac316cbfad3cdc62259171e182"
    url = "https://github.com/JuliaBinaryWrappers/libidn_jll.jl/releases/download/libidn-v1.44.0+0/libidn.v1.44.0.powerpc64le-linux-gnu.tar.gz"
[[libidn]]
arch = "riscv64"
git-tree-sha1 = "d03a59b5f06f24a65ef7471b98304368a7154cf5"
libc = "glibc"
os = "linux"

    [[libidn.download]]
    sha256 = "fd983319df876d9769a657e6fb948cb58ca0cfa16c2b1eaa2e141cb200e518bf"
    url = "https://github.com/JuliaBinaryWrappers/libidn_jll.jl/releases/download/libidn-v1.44.0+0/libidn.v1.44.0.riscv64-linux-gnu.tar.gz"
[[libidn]]
arch = "x86_64"
git-tree-sha1 = "e6fc44a380456a7e581fc0888f3b7b39804de2ff"
os = "macos"

    [[libidn.download]]
    sha256 = "813ddedcebd9b675d6e9bf700935d6571759c2e5841e9235993d7858bea651f3"
    url = "https://github.com/JuliaBinaryWrappers/libidn_jll.jl/releases/download/libidn-v1.44.0+0/libidn.v1.44.0.x86_64-apple-darwin.tar.gz"
[[libidn]]
arch = "x86_64"
git-tree-sha1 = "39d71253b8dec6ad61046769f84cd31c04400da8"
libc = "glibc"
os = "linux"

    [[libidn.download]]
    sha256 = "0e996c770867bb7a166b277045109024045df41bdc759660ed374d3201ab50d2"
    url = "https://github.com/JuliaBinaryWrappers/libidn_jll.jl/releases/download/libidn-v1.44.0+0/libidn.v1.44.0.x86_64-linux-gnu.tar.gz"
[[libidn]]
arch = "x86_64"
git-tree-sha1 = "adf20bb205d0daafc697851d83e10031ea847942"
libc = "musl"
os = "linux"

    [[libidn.download]]
    sha256 = "96d25aa6c50d39e97da7a66a2187ed49c1f2d00f1bae233248a8c93846446d5d"
    url = "https://github.com/JuliaBinaryWrappers/libidn_jll.jl/releases/download/libidn-v1.44.0+0/libidn.v1.44.0.x86_64-linux-musl.tar.gz"
[[libidn]]
arch = "x86_64"
git-tree-sha1 = "e8f5e5f067594a4dc63fb35e0b940e4ee680012d"
os = "freebsd"

    [[libidn.download]]
    sha256 = "c4c49298ec171ab9f94b0add51667917315b2c6595ec2156d04cbc3da079c7a7"
    url = "https://github.com/JuliaBinaryWrappers/libidn_jll.jl/releases/download/libidn-v1.44.0+0/libidn.v1.44.0.x86_64-unknown-freebsd.tar.gz"
[[libidn]]
arch = "x86_64"
git-tree-sha1 = "0ae28e5ff70c41cd2af00de917bfd9c1b6da6bf9"
os = "windows"

    [[libidn.download]]
    sha256 = "ec122079ffba758dd934430dcbb0b89d8f7c334ef951120e67004d8b32e235f5"
    url = "https://github.com/JuliaBinaryWrappers/libidn_jll.jl/releases/download/libidn-v1.44.0+0/libidn.v1.44.0.x86_64-w64-mingw32.tar.gz"
